const TOPICS = ['Measurements and their errors','Particles and radiation','Waves','Mechanics and materials','Electricity','Further mechanics and thermal physics','Fields and their consequences','Nuclear physics','Astrophysics','Medical physics','Engineering physics','Turning points in physics','Electronics','Practical skills and data analysis'];
const QUESTIONS = [];
function numeric(topic, level, title, prompt, answer, unit, steps, marks=3, diagram=null) {
  QUESTIONS.push({id:`q${QUESTIONS.length+1}`,topic,level:['Foundation','Standard','Challenge'][level],title,prompt,answer,unit,steps,marks,type:'numeric',diagram});
}
function choice(topic, level, title, prompt, options, answer, steps) {
  QUESTIONS.push({id:`q${QUESTIONS.length+1}`,topic,level:['Foundation','Standard','Challenge'][level],title,prompt,options,answer,steps,marks:1,type:'choice'});
}
function written(topic, level, title, prompt, steps, marks=4) {
  QUESTIONS.push({id:`q${QUESTIONS.length+1}`,topic,level:['Foundation','Standard','Challenge'][level],title,prompt,steps,marks,type:'written'});
}
numeric(0,0,'Percentage uncertainty','A length is measured as 25.0 cm with an absolute uncertainty of 0.2 cm. Calculate the percentage uncertainty.',0.8,'%', ['Percentage uncertainty = (absolute uncertainty / measured value) x 100.','(0.2 / 25.0) x 100 = 0.80%.'],2);
numeric(0,1,'Uncertainty in density','A cylinder has mass m, radius r and length L. Their percentage uncertainties are 1%, 2% and 3% respectively. Using density = m / (pi r squared L), calculate the percentage uncertainty in density.',8,'%', ['For products and quotients, add percentage uncertainties.','The squared radius contributes 2 x 2% = 4%.','Total = 1% + 4% + 3% = 8%.']);
numeric(0,2,'Finding g from a gradient','A graph of pendulum period squared, T squared, against length L has gradient 4.03 s squared per metre. The gradient uncertainty is 0.08 s squared per metre. Use T squared = 4 pi squared L / g to calculate the absolute uncertainty in g.',0.194,'m s^-2',['g = 4 pi squared / 4.03 = 9.80 m s^-2.','Fractional uncertainty in g equals fractional uncertainty in the gradient: 0.08 / 4.03.','Absolute uncertainty = 9.80 x 0.08 / 4.03 = 0.194 m s^-2.'],4);
choice(1,0,'Quark structure','Which quark combination describes a proton?',['udd','uud','uuu','ddd'],1,['A proton contains two up quarks and one down quark.','Charge = 2/3 + 2/3 - 1/3 = +1 elementary charge.']);
numeric(1,1,'Photon energy','Light of wavelength 450 nm is incident on a surface. Calculate the energy of one photon in joules. Use h = 6.63 x 10^-34 J s and c = 3.00 x 10^8 m s^-1.',4.42e-19,'J',['Convert wavelength: 450 nm = 4.50 x 10^-7 m.','E = hc / wavelength.','E = (6.63 x 10^-34 x 3.00 x 10^8) / (4.50 x 10^-7) = 4.42 x 10^-19 J.']);
numeric(1,2,'Photoelectric stopping potential','A metal has a work function of 2.20 eV. Light of wavelength 350 nm illuminates it. Calculate the stopping potential. Use h = 6.63 x 10^-34 J s, c = 3.00 x 10^8 m s^-1 and e = 1.60 x 10^-19 C.',1.352,'V',['Photon energy = hc / wavelength = 5.68 x 10^-19 J = 3.55 eV.','Maximum kinetic energy = photon energy - work function = 1.35 eV.','eV_stop = maximum kinetic energy, so V_stop = 1.35 V.'],4);
numeric(2,0,'Wave speed','A wave has frequency 250 Hz and wavelength 1.36 m. Calculate its speed.',340,'m s^-1',['v = f x wavelength.','v = 250 x 1.36 = 340 m s^-1.'],2,'wave');
numeric(2,1,'Double-slit fringes','In a double-slit experiment, light of wavelength 600 nm passes through slits separated by 0.30 mm. The screen is 2.0 m away. Calculate the fringe spacing in millimetres.',4,'mm',['Fringe spacing w = wavelength x D / s.','w = (600 x 10^-9 x 2.0) / (0.30 x 10^-3) = 0.0040 m.','0.0040 m = 4.0 mm.']);
numeric(2,2,'Diffraction orders','A diffraction grating has 600 lines per millimetre. Monochromatic light of wavelength 550 nm is incident normally. Calculate the highest possible order of maximum.',3,'order',['Grating spacing d = 1 / (600 x 1000) = 1.667 x 10^-6 m.','n x wavelength = d sin(theta), with sin(theta) at most 1.','n is at most d / wavelength = 3.03. The highest integer order is 3.']);
numeric(3,0,'Accelerating a trolley','A trolley of mass 1.5 kg experiences a resultant horizontal force of 3.6 N. Calculate its acceleration.',2.4,'m s^-2',['Resultant force F = ma.','a = F / m = 3.6 / 1.5 = 2.4 m s^-2.'],2);
numeric(3,1,'Energy stored in a wire','A wire obeys Hooke\'s law. A tensile force of 80 N produces an extension of 1.5 mm. Calculate the elastic strain energy stored.',0.06,'J',['Elastic strain energy = 1/2 x force x extension.','Extension = 1.5 x 10^-3 m.','Energy = 0.5 x 80 x 1.5 x 10^-3 = 0.060 J.']);
numeric(3,2,'A collision and a climb','A 0.020 kg projectile travelling horizontally at 150 m s^-1 embeds in a stationary 0.480 kg block. The combined mass then moves up a frictionless slope. Calculate its maximum vertical rise. Use g = 9.81 m s^-2.',1.835,'m',['Conserve momentum during impact: 0.020 x 150 = 0.500 v, so v = 6.00 m s^-1.','After impact, kinetic energy converts to gravitational potential energy.','1/2 mv squared = mgh, so h = 6.00 squared / (2 x 9.81) = 1.83 m.','Kinetic energy is not conserved during the inelastic collision.'],5);
numeric(4,0,'Current in a resistor','A potential difference of 12 V is applied across a 30 ohm resistor. Calculate the current.',0.4,'A',['V = IR.','I = 12 / 30 = 0.40 A.'],2);
numeric(4,1,'Internal resistance','A cell has emf 1.50 V. Its terminal potential difference is 1.20 V when delivering a current of 0.60 A. Calculate its internal resistance.',0.5,'ohm',['Terminal potential difference V = emf - Ir.','r = (1.50 - 1.20) / 0.60 = 0.50 ohm.']);
numeric(4,2,'A loaded potential divider','Two 2.0 kilo-ohm resistors form a potential divider across an ideal 12 V supply. A 4.0 kilo-ohm load is connected in parallel with the lower resistor. Calculate the potential difference across the load.',4.8,'V',['Lower equivalent resistance = (2000 x 4000) / (2000 + 4000) = 1333 ohm.','Total resistance = 2000 + 1333 = 3333 ohm.','Output voltage = 12 x 1333 / 3333 = 4.80 V.'],4);
numeric(5,0,'Heating water','Calculate the energy needed to heat 0.50 kg of water by 20 K. The specific heat capacity is 4200 J kg^-1 K^-1. Ignore heat losses.',42000,'J',['Q = mc x temperature change.','Q = 0.50 x 4200 x 20 = 42000 J.'],2);
numeric(5,1,'Maximum SHM speed','A body undergoes simple harmonic motion with amplitude 0.080 m and frequency 2.5 Hz. Calculate its maximum speed.',1.2566,'m s^-1',['Angular frequency = 2 pi f = 15.7 rad s^-1.','Maximum speed = angular frequency x amplitude.','v_max = 15.7 x 0.080 = 1.26 m s^-1.']);
numeric(5,2,'Molecular speeds','Nitrogen has molar mass 0.028 kg mol^-1. Calculate the root mean square speed of its molecules at 300 K. Use R = 8.31 J mol^-1 K^-1.',516.8,'m s^-1',['From kinetic theory, 1/2 m c_rms squared = 3/2 kT.','In molar form, c_rms = square root of (3RT / M).','c_rms = square root of (3 x 8.31 x 300 / 0.028) = 517 m s^-1.'],4);
numeric(6,0,'Electric field strength','Parallel conducting plates have a potential difference of 600 V and separation of 0.020 m. Calculate the magnitude of the uniform electric field between them.',30000,'V m^-1',['E = V / d.','E = 600 / 0.020 = 30000 V m^-1.'],2);
numeric(6,1,'A discharging capacitor','A 100 microfarad capacitor discharges through a 20 kilo-ohm resistor. Initially its potential difference is 12 V. Calculate the potential difference after 3.0 s.',2.678,'V',['Time constant RC = 20000 x 100 x 10^-6 = 2.0 s.','V = V_0 exp(-t / RC).','V = 12 exp(-3.0 / 2.0) = 2.68 V.']);
numeric(6,2,'Orbit above Earth','Calculate the period of a circular satellite orbit at a height of 400 km above Earth. Use Earth radius 6.37 x 10^6 m, Earth mass 5.97 x 10^24 kg and G = 6.67 x 10^-11 N m^2 kg^-2.',5546,'s',['Orbital radius r = 6.37 x 10^6 + 4.00 x 10^5 = 6.77 x 10^6 m.','Equate gravitational and centripetal forces to get T = 2 pi square root of (r cubed / GM).','T = 5.55 x 10^3 s (about 92.4 minutes).'],4);
numeric(7,0,'Half-life','A radioactive source has an initial activity of 800 Bq and a half-life of 6.0 hours. Calculate its activity after 18 hours.',100,'Bq',['18 / 6 = 3 half-lives.','Activity = 800 / 2 cubed = 100 Bq.'],2);
numeric(7,1,'Decay constant','A radioactive isotope has a half-life of 20 minutes. Calculate its decay constant in s^-1.',0.0005776,'s^-1',['Half-life = 20 x 60 = 1200 s.','Decay constant = ln(2) / half-life.','Decay constant = 0.693 / 1200 = 5.78 x 10^-4 s^-1.']);
numeric(7,2,'Binding energy per nucleon','A helium-4 nucleus has mass 4.001506 u. Proton and neutron masses are 1.007276 u and 1.008665 u. Calculate the binding energy per nucleon. Use 1 u = 931.5 MeV/c squared.',7.0739,'MeV',['Mass defect = 2(1.007276) + 2(1.008665) - 4.001506 = 0.030376 u.','Binding energy = 0.030376 x 931.5 = 28.296 MeV.','Divide by 4 nucleons: 7.074 MeV per nucleon.'],4);
numeric(8,0,'Stellar temperature','A star has peak emission wavelength 500 nm. Calculate its surface temperature. Use Wien\'s constant = 2.90 x 10^-3 m K.',5800,'K',['Peak wavelength x temperature = 2.90 x 10^-3.','T = (2.90 x 10^-3) / (500 x 10^-9) = 5800 K.'],2);
numeric(8,1,'Stellar luminosity','A star has twice the radius of the Sun and a surface temperature 1.5 times that of the Sun. Calculate its luminosity as a multiple of the Sun\'s luminosity.',20.25,'times solar',['Luminosity is proportional to radius squared x temperature to the fourth power.','Luminosity ratio = 2 squared x 1.5 to the fourth power = 20.25.']);
numeric(8,2,'Resolving a binary star','A telescope observes at wavelength 550 nm. Two stars have angular separation 2.0 x 10^-6 rad. Using the Rayleigh criterion theta = 1.22 wavelength / D, calculate the minimum aperture diameter needed to resolve them.',0.3355,'m',['Rearrange the supplied criterion: D = 1.22 x wavelength / theta.','D = (1.22 x 550 x 10^-9) / (2.0 x 10^-6) = 0.336 m.']);
numeric(9,0,'Ultrasound echoes','An ultrasound pulse returns from a boundary after 80 microseconds. The speed of ultrasound in the tissue is 1540 m s^-1. Calculate the depth of the boundary.',0.0616,'m',['The pulse travels to the boundary and back.','Depth = vt / 2 = 1540 x 80 x 10^-6 / 2 = 0.0616 m.'],2);
numeric(9,1,'X-ray attenuation','A material has a linear attenuation coefficient of 0.15 mm^-1. Calculate the fraction of incident X-ray intensity transmitted through 8.0 mm of the material.',0.3012,'fraction',['I / I_0 = exp(-mu x).','I / I_0 = exp(-0.15 x 8.0) = 0.301.']);
numeric(9,2,'Acoustic reflection','Ultrasound crosses normally from tissue with acoustic impedance 1.5 x 10^6 kg m^-2 s^-1 into bone with impedance 7.8 x 10^6 kg m^-2 s^-1. Calculate the percentage of incident intensity reflected. Use R = ((Z_2 - Z_1) / (Z_2 + Z_1)) squared.',45.89,'%', ['R = ((7.8 - 1.5) / (7.8 + 1.5)) squared.','R = (6.3 / 9.3) squared = 0.459.','Percentage reflected = 45.9%.']);
numeric(10,0,'Turning moment','A force of 40 N acts perpendicular to a lever at a distance of 0.25 m from its pivot. Calculate the torque.',10,'N m',['Torque = force x perpendicular distance.','Torque = 40 x 0.25 = 10 N m.'],2);
numeric(10,1,'Flywheel energy','A flywheel has moment of inertia 0.80 kg m squared and angular speed 30 rad s^-1. Calculate its rotational kinetic energy.',360,'J',['Rotational kinetic energy = 1/2 I omega squared.','Energy = 0.5 x 0.80 x 30 squared = 360 J.']);
numeric(10,2,'Braking a flywheel','A flywheel with moment of inertia 1.2 kg m squared initially rotates at 50 rad s^-1. A constant braking torque of 6.0 N m brings it to rest. Calculate the number of revolutions made while stopping.',39.789,'revolutions',['Angular deceleration magnitude = torque / I = 6.0 / 1.2 = 5.0 rad s^-2.','Use omega squared = omega_0 squared + 2 alpha theta: theta = 250 rad.','Number of revolutions = 250 / (2 pi) = 39.8.'],4);
numeric(11,0,'Electron wavelength','An electron has momentum 3.0 x 10^-24 kg m s^-1. Calculate its de Broglie wavelength. Use h = 6.63 x 10^-34 J s.',2.21e-10,'m',['Wavelength = h / p.','Wavelength = (6.63 x 10^-34) / (3.0 x 10^-24) = 2.21 x 10^-10 m.'],2);
numeric(11,1,'Relativistic time dilation','A particle has a proper mean lifetime of 2.2 microseconds and travels at 0.80c relative to the laboratory. Calculate its mean lifetime in the laboratory frame.',3.6667,'microseconds',['Lorentz factor = 1 / square root of (1 - 0.80 squared) = 1.667.','Laboratory lifetime = Lorentz factor x proper lifetime.','Lifetime = 1.667 x 2.2 = 3.67 microseconds.']);
numeric(11,2,'Accelerating electrons','Electrons are accelerated from rest through 2500 V. Calculate their de Broglie wavelength, assuming non-relativistic motion. Use h = 6.63 x 10^-34 J s, m_e = 9.11 x 10^-31 kg and e = 1.60 x 10^-19 C.',2.456e-11,'m',['Kinetic energy = eV, and momentum p = square root of (2 m_e eV).','p = square root of (2 x 9.11 x 10^-31 x 1.60 x 10^-19 x 2500) = 2.70 x 10^-23 kg m s^-1.','Wavelength = h / p = 2.46 x 10^-11 m.'],4);
choice(12,0,'Logic gates','Which gate has output 1 only when both of its two inputs are 1?',['OR','AND','NAND','XOR'],1,['An AND gate gives 1 only for the input combination 1, 1.']);
numeric(12,1,'Inverting amplifier','An ideal inverting operational amplifier has input resistance 10 kilo-ohm and feedback resistance 47 kilo-ohm. The input is +0.20 V. Calculate the output voltage, assuming no saturation.',-0.94,'V',['Voltage gain = -R_feedback / R_input = -47 / 10 = -4.7.','Output = -4.7 x 0.20 = -0.94 V.']);
numeric(12,2,'A summing amplifier','An ideal inverting summing amplifier has feedback resistance 100 kilo-ohm. Inputs of +0.10 V and +0.20 V enter through resistances of 20 kilo-ohm and 50 kilo-ohm respectively. Calculate the output voltage. Assume no saturation.',-0.9,'V',['The inverting input is at virtual earth. Input currents are 0.10 / 20000 = 5 microamps and 0.20 / 50000 = 4 microamps.','Total feedback current = 9 microamps.','V_out = -100000 x 9 x 10^-6 = -0.90 V.'],4);
numeric(13,0,'Mean period','A student measures the time for 20 complete pendulum oscillations as 28.4 s. Calculate the mean period of one oscillation.',1.42,'s',['Period = total time / number of oscillations.','T = 28.4 / 20 = 1.42 s.'],2);
written(13,1,'Measuring wire resistivity','Describe how to determine the resistivity of a uniform metal wire using electrical measurements. Include how to measure its dimensions and reduce heating effects.',['Measure the wire diameter with a micrometer at several positions and orientations; calculate the mean diameter and A = pi d squared / 4.','Measure the length L between the voltage contacts using a metre rule.','Connect an ammeter in series and a voltmeter across the measured length. Determine resistance R from V / I or the gradient of a V-against-I graph.','Use resistivity = RA / L. Keep current low and switch off between readings to limit temperature changes.']);
written(13,2,'Testing an inverse-square law','A student investigates how the count rate from a small gamma source varies with distance. Explain how they could test an inverse-square relationship while accounting for background radiation and random uncertainty.',['Measure background counts over a long, recorded time without the source; convert to a background count rate.','Measure counts over recorded times at several distances from the source to the detector, keeping alignment fixed. Use distances large compared with source and detector dimensions.','Subtract the background count rate from each measured count rate. Repeat or count for longer to reduce relative random uncertainty.','Plot corrected count rate against 1 / distance squared. A straight line through the origin, within uncertainty, supports the relationship.','For N independent counts, the count uncertainty is approximately square root of N; account for the background uncertainty as well.','Handle the source with tongs, minimise exposure time, maximise distance and return it to appropriate shielding when not in use.'],6);
